// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Supabase: when using the pooler in DATABASE_URL, set DIRECT_URL to the
    // direct (non-pooled) connection. Wire this in when we adopt Prisma 7's
    // adapter pattern; for now, point DATABASE_URL straight at the direct
    // connection during migrations.
  },
});
