import type { Metadata } from "next";
import { Suspense } from "react";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { FlashToast } from "@/components/flash-toast";
import { FormGuard } from "@/components/form-guard";
import RecoveryHashRedirect from "./RecoveryHashRedirect";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Catch a Supabase recovery/invite redirect that lands with tokens in
            the URL hash on any page and forward it to /agent/set-password. */}
        <RecoveryHashRedirect />
        {children}
        {/* FormGuard reads useSearchParams to detect server-action
            redirects and restore stuck "Saving…" buttons; wrap in
            Suspense so this client hook doesn't de-opt the whole app
            to client-side rendering. */}
        <Suspense fallback={null}>
          <FormGuard />
        </Suspense>
        <FlashToast />
      </body>
    </html>
  );
}
