// Extracts the Chart of Accounts from docs/F.S March 2026.xlsx into a TS
// seed file at prisma/seed/chart-of-accounts.ts. Run once whenever the
// workbook's CoA changes; commit the resulting seed file.
//
// Layout (verified): header at r2, data r3..end, cols A=SL, B=Accounts Name,
// C=Normal Balance ('DEBIT'|'CREDIT').
import ExcelJS, { type CellRichTextValue, type CellFormulaValue } from "exceljs";
import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";

const SOURCE = path.resolve("docs/F.S March 2026.xlsx");
const TARGET = path.resolve("prisma/seed/chart-of-accounts.ts");

type Row = { sl: number | null; name: string; normalBalance: "DEBIT" | "CREDIT" };

function cellText(value: ExcelJS.CellValue): string {
  if (value === null || value === undefined) return "";
  if (typeof value === "string") return value;
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (value instanceof Date) return value.toISOString();
  if (typeof value === "object") {
    // Rich text: { richText: [{ text: '...' }, ...] }
    const rt = value as Partial<CellRichTextValue>;
    if (Array.isArray(rt.richText)) return rt.richText.map((p) => p.text).join("");
    // Formula: { result: ..., formula: '...' }
    const fv = value as Partial<CellFormulaValue>;
    if (fv.result !== undefined) return cellText(fv.result as ExcelJS.CellValue);
    // Hyperlink: { text: '...', hyperlink: '...' }
    if ("text" in value && typeof (value as { text: unknown }).text === "string") {
      return (value as { text: string }).text;
    }
  }
  return "";
}

async function main() {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.readFile(SOURCE);

  const sheet = wb.getWorksheet("Chart of Accounts");
  if (!sheet) throw new Error("Sheet 'Chart of Accounts' not found");

  const rows: Row[] = [];
  const seenNames = new Set<string>();
  const issues: string[] = [];
  let nextSl = 0;

  for (let r = 3; r <= sheet.rowCount; r++) {
    const row = sheet.getRow(r);
    const slRaw = cellText(row.getCell(1).value).trim();
    const name = cellText(row.getCell(2).value).trim();
    const nbRaw = cellText(row.getCell(3).value).trim().toUpperCase();

    if (!name) continue; // blank row

    const sl = slRaw ? Number(slRaw) : null;
    if (sl !== null && Number.isFinite(sl)) nextSl = Math.max(nextSl, sl);

    if (nbRaw !== "DEBIT" && nbRaw !== "CREDIT") {
      issues.push(`r${r}: "${name}" → unrecognised normal balance "${nbRaw}"`);
      continue;
    }

    if (seenNames.has(name)) {
      issues.push(`r${r}: duplicate account name "${name}" (DB unique constraint will fail)`);
      continue;
    }
    seenNames.add(name);

    rows.push({ sl, name, normalBalance: nbRaw });
  }

  // Backfill SL for rows missing it (late additions in the workbook). Keep
  // numbering monotonic so the seeded order matches the auditor's mental model.
  for (const row of rows) {
    if (row.sl === null) {
      nextSl += 1;
      row.sl = nextSl;
    }
  }

  console.log(`Extracted ${rows.length} accounts`);
  if (issues.length) {
    console.log(`\nIssues (${issues.length}):`);
    for (const i of issues) console.log("  -", i);
  }

  mkdirSync(path.dirname(TARGET), { recursive: true });
  const ts = renderSeed(rows);
  writeFileSync(TARGET, ts, "utf8");
  console.log(`\nWrote ${TARGET}`);
}

function renderSeed(rows: Row[]): string {
  const banner = `// AUTO-GENERATED by scripts/extract-chart-of-accounts.ts.
// Source: docs/F.S March 2026.xlsx → 'Chart of Accounts' sheet.
// Re-run the extractor whenever the workbook's CoA changes; do not edit
// this file by hand.

export type SeedAccount = {
  sl: number;
  name: string;
  normalBalance: "DEBIT" | "CREDIT";
};

export const CHART_OF_ACCOUNTS_SEED: SeedAccount[] = [
`;
  const body = rows
    .map(
      (r) =>
        `  { sl: ${r.sl}, name: ${JSON.stringify(r.name)}, normalBalance: "${r.normalBalance}" },`,
    )
    .join("\n");
  return `${banner}${body}\n];\n`;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
